# Generated by Django 5.2.4 on 2026-05-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name', 'section'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'section')},
        ),
    ]
