# Generated by Django 5.2.4 on 2026-05-14 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('current_semester', models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semester')], default='FIRST', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_fr', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2024', max_length=10)),
                ('semester', models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semester')], max_length=10)),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='students.class')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('class_assigned', 'academic_year', 'semester', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='InstallmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_reminded', models.BooleanField(default=False)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.installmentplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Excellence'), ('SPORTS', 'Sports'), ('NEED_BASED', 'Need Based'), ('MERIT', 'Merit'), ('SPECIAL', 'Special')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_percentage', models.BooleanField(default=True)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applies_to_semester', models.CharField(choices=[('YEARLY', 'Yearly (Both Semesters)'), ('FIRST', '1st Semester Only'), ('SECOND', '2nd Semester Only')], default='YEARLY', max_length=20)),
                ('max_students', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applies_to_categories', models.ManyToManyField(blank=True, to='fees.feecategory')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2024', max_length=10)),
                ('semester', models.CharField(choices=[('YEARLY', 'Yearly (Both Semesters)'), ('FIRST', '1st Semester'), ('SECOND', '2nd Semester')], max_length=10)),
                ('total_amount_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_applied_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_applied_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_yearly_payment', models.BooleanField(default=False)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledger', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2024', max_length=10)),
                ('approved_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.scholarshiptype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2024', max_length=10)),
                ('semester', models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semester')], max_length=10)),
                ('student_type', models.CharField(choices=[('NEW', 'New Student'), ('OLD', 'Returning Student')], max_length=10)),
                ('amount_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feecategory')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.class')),
            ],
            options={
                'unique_together': {('class_assigned', 'academic_year', 'semester', 'student_type', 'category')},
            },
        ),
    ]
