# Generated by Django 5.2.4 on 2026-05-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='amount_lrd',
            new_name='semester1_amount_lrd',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='amount_usd',
            new_name='semester1_amount_usd',
        ),
        migrations.RenameField(
            model_name='studentfeeledger',
            old_name='amount_paid_lrd',
            new_name='semester1_paid_lrd',
        ),
        migrations.RenameField(
            model_name='studentfeeledger',
            old_name='amount_paid_usd',
            new_name='semester1_paid_usd',
        ),
        migrations.RenameField(
            model_name='studentfeeledger',
            old_name='total_amount_lrd',
            new_name='semester1_total_lrd',
        ),
        migrations.RenameField(
            model_name='studentfeeledger',
            old_name='total_amount_usd',
            new_name='semester1_total_usd',
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('class_assigned', 'academic_year', 'student_type', 'category')},
        ),
        migrations.RemoveField(
            model_name='studentfeeledger',
            name='is_fully_paid',
        ),
        migrations.RemoveField(
            model_name='studentfeeledger',
            name='is_yearly_payment',
        ),
        migrations.RemoveField(
            model_name='studentfeeledger',
            name='semester',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='semester2_amount_lrd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='semester2_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='yearly_amount_lrd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='yearly_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='studentfeeledger',
            name='payment_for',
            field=models.CharField(choices=[('YEARLY', 'Yearly (Both Semesters)'), ('FIRST', '1st Semester'), ('SECOND', '2nd Semester')], default='FIRST', max_length=10),
        ),
        migrations.AddField(
            model_name='studentfeeledger',
            name='semester2_paid_lrd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='studentfeeledger',
            name='semester2_paid_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='studentfeeledger',
            name='semester2_total_lrd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='studentfeeledger',
            name='semester2_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='semester',
        ),
    ]
