# Generated by Django 5.2.4 on 2026-05-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_rename_amount_lrd_feestructure_semester1_amount_lrd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='yearly_amount_lrd',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='yearly_amount_usd',
        ),
        migrations.RemoveField(
            model_name='studentfeeledger',
            name='payment_for',
        ),
    ]
