# Generated by Django 5.2.4 on 2026-05-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_photo',
            field=models.ImageField(blank=True, help_text='Upload photo of receipt or invoice', null=True, upload_to='expenses/%Y/%m/%d/'),
        ),
    ]
