# Generated by Django 4.2 on 2026-05-21 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(default='accountant', max_length=50)),
                ('total_receipts', models.IntegerField(default=0)),
                ('total_amount_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField(editable=False, unique=True)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('amount_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money')], default='CASH', max_length=20)),
                ('payment_period', models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semester'), ('YEARLY', 'Yearly (Both Semesters)')], default='FIRST', max_length=10)),
                ('mobile_transaction_id', models.CharField(blank=True, max_length=100)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True)),
                ('is_legacy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feecategory')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receipts.receipt')),
            ],
        ),
    ]
