# Generated by Django 5.2.4 on 2026-05-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(default='accountant', max_length=50)),
                ('total_receipts', models.IntegerField(default=0)),
                ('total_amount_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
