# Generated by Django 4.2 on 2026-06-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchPaymentSession',
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='semester',
            field=models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semester'), ('YEARLY', 'Yearly (Both Semesters)')], default='FIRST', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
