# Generated by Django 4.2 on 2026-05-21 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receipt_is_legacy_paymentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_period',
            field=models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semester'), ('YEARLY', 'Yearly (Both Semesters)')], default='FIRST', max_length=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
