# Generated by Django 4.2 on 2026-05-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='piece', help_text='e.g., piece, dozen, ream, box', max_length=20)),
                ('unit_price_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In - Purchase'), ('OUT', 'Stock Out - Issued'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit_price_lrd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Receipt number, teacher name, etc.', max_length=100)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(default='accountant', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
            ],
        ),
    ]
