# Generated by Django 4.2 on 2026-05-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_staffperformancereview_staffattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffperformancereview',
            name='rating',
            field=models.IntegerField(help_text='1=Poor, 5=Excellent'),
        ),
        migrations.AlterField(
            model_name='staffperformancereview',
            name='review_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
